["pyproject.toml".tool.poetry.dependencies]
python = "^3.6"

["pyproject.toml".tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.14.0"                    # Linting
mypy = "^0.770"                                         # Linting
black = "^19.10b0"                                      # Formatting
isort = { version = "^4.3.0", extras = ["pyproject"] }  # Formatting
pytest = "^5.4.0"                                       # Runnning Tests
tox = "^3.15.2"                                         # Tox Testing
tox-pyenv = "^1.1.0"                                    # Tox Testing

# Pre-commit - helps enforce code style. Use `pre-commit install` to install
pre-commit = { version = "^2.5.0", python = "^3.6.1" }

["pyproject.toml".build-system]
requires = ["poetry>=1.0", "pip>=20.0"]
build-backend = "poetry.masonry.api"
