[nitpick]
minimum_version = "0.10"

[nitpick.styles]
include = [
  "styles/file-structure.toml",
  "styles/poetry.toml",
  "styles/pytest.toml",
  "styles/black.toml",
  "styles/isort.toml",
  "styles/unimport.toml",
  "styles/flake8.toml",
  "styles/mypy.toml",
  "styles/darglint.toml",
  "styles/pre-commit.toml",
]

[nitpick.files."setup.cfg"]
comma_separated_values = [
  "flake8.exclude",
]