[nitpick]
minimum_version = "0.10"

[nitpick.styles]
include = [
  "styles/file-structure.toml",
  "styles/poetry.toml",
  "styles/flake8.toml",
  "styles/black.toml",
  "styles/mypy.toml",
  "styles/isort.toml",
  "styles/pre-commit.toml",
  "styles/unimport.toml",
  "styles/darglint.toml",
]

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.21.4
    hooks:
      - id: nitpick
        additional_dependencies: ["toml==0.10.0"]
"""
