["pyproject.toml".tool.unimport]
exclude = '(__init__.py)'
include = '^tests'

[["pre-commit-config.yaml".repos]]
yaml = """
    - repo: https://github.com/hakancelik96/unimport
    rev: v0.2.7
    hooks:
    - id: unimport
        additional_dependencies: [toml]
        args: [-c, pyproject.toml, -r, --include-star-import]
"""
