name: Pull Request

# Trigger the workflow on pull request to either master or develop branch
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v2

      - name: Poetry Lock (For Windows Only)
        if: startsWith(runner.os, 'Windows')
        run: poetry lock -v
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Setup Linting
        run: pip install tox

      - name: Run Linting
        run: tox -e lint

  testing:
    name: Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v2

      - name: Poetry Lock (For Windows Only)
        if: startsWith(runner.os, 'Windows')
        run: poetry lock -v
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Setup Testing
        run: pip install tox tox-gh-actions

      - name: Run Tests
        run: tox
