name: Pull Request

# Trigger the workflow on pull request to master branch
on:
  pull_request:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Run Linting
        run: |
          pip install --upgrade pip
          pip install tox
          tox -e lint

  Testing:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.6, 3.7, 3.8]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Run Tests
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions
          tox
