name: Push

# Trigger the workflow on push to the master or develop branch.
# These branches are protected, so will run when a PR is merged
on:
  push:
    branches:
      - master
      - develop

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.7, 3.8]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v2

      - name: Poetry Lock (For Windows Only)
        if: startsWith(runner.os, 'Windows')
        run: poetry lock -v
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Setup Testing
        run: pip install tox tox-gh-actions

      - name: Run Tests
        run: tox

  release:
    name: Release
    needs: testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v2

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/exec @semantic-release/git

      - name: Release
        # See the following about pushing sematic-release changes to a protected branch
        # https://github.com/semantic-release/github/issues/175#issuecomment-484964034
        # https://github.com/semantic-release/github/issues/175#issuecomment-559004304
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.TEC_DEVBOT_ACCESS_TOKEN}}
          POETRY_VIRTUALENVS_CREATE: false
