# Other Poetry Sections

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.14"                    # Linting
mypy = "^0.770"                                       # Linting
black = "^19.10b0"                                    # Formatting
isort = { version = "^4.3", extras = ["pyproject"] }  # Formatting
pytest = "^5.4"                                       # Runnning Tests
tox = "^3.15"                                         # Tox Testing
tox-pyenv = "^1.1"                                    # Tox Testing
nitpick = "^0.21"                                     # Style Guide
toml = "<0.10.1"                                      # Style Guide

# Pre-commit - helps enforce code style. Use `pre-commit install` to install
pre-commit = "^2.5"

[[tool.poetry.source]]
name = "flow-pypi"
url = "http://flow-pypi.herokuapp.com/simple/"

[tool.nitpick]
style = "https://raw.githubusercontent.com/theengineeringco/python-styleguide/master/TEC-style.toml"

[tool.black]
line-length = 120
target-version = ["py36"]

[tool.isort]
line_length = 120
multi_line_output = 3
indent = 4
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_third_party = []

[tool.unimport]
include = '^<package_name>|^tests'
exclude = '(__init__.py)'

[build-system]
requires = ["poetry>=1.0", "pip>=20.0"]
build-backend = "poetry.masonry.api"
