["pyproject.toml".tool.black]
line-length = 120
target-version = ["py38"]

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/python/black
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    hooks:
      - id: blacken-docs
"""
