["setup.cfg".flake8]
format = "default"
max-arguments = 10
max-complexity = 20
max-line-complexity = 16
max-line-length = 120
max-local-variables = 10
max-methods = 10
max-module-members = 15

extend-ignore = "D1, RST, Q000, E800, EXE002, C101, WPS100, WPS110, WPS300, WPS331, WPS410, WPS412, WPS420, WPS421, WPS428"