["pyproject.toml".tool.isort]
line_length = 120
profile     = "black"

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/timothycrosley/isort
    hooks:
      - id: isort
"""
