["pyproject.toml".tool.isort]
line_length = 120
multi_line_output = 3
indent = 4
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/timothycrosley/isort
    hooks:
      - id: isort
"""
