["setup.cfg".mypy]
python_version         = 3.8
ignore_missing_imports = true
strict_optional        = true
warn_redundant_casts   = true
warn_unused_ignores    = true
warn_no_return         = true
warn_unreachable       = true
check_untyped_defs     = true
implicit_reexport      = false
strict_equality        = true
