["setup.cfg".mypy]
python_version = 3.6
ignore_missing_imports = true
follow_imports = "skip"
strict_optional = true
warn_no_return = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
