["pyproject.toml".tool.poetry.dependencies]
python = "^3.6"

["pyproject.toml".tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.14"
mypy = "^0.770"
black = "^19.10b0"
isort = { version = "^4.3", extras = ["pyproject"] }
pytest = "^5.4"
tox = "^3.15"
tox-pyenv = "^1.1"
nitpick = "^0.21"
toml = "<0.10.1"
pre-commit = { version = "^2.5", python = "^3.6.1" }

["pyproject.toml".build-system]
requires = ["poetry-core>=1.0.0", "pip>=20.0"]
build-backend = "poetry.core.masonry.api"
