["pyproject.toml".tool.poetry.dependencies]
python = "^3.8"

["pyproject.toml".tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.15"
mypy                     = "^0.780"
black                    = "^20.8b1"
isort                    = "^5.0"
pytest                   = "^6.0"
tox                      = "^3.20"
pre-commit               = "^2.10"

[["pyproject.toml".tool.poetry.source]]
name = "tec-pypi"
url  = "https://pypi.theengineering.company"

["pyproject.toml".build-system]
build-backend = "poetry.core.masonry.api"
