["pyproject.toml".tool.poetry.dependencies]
python = "^3.8"

["pyproject.toml".tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.14"
mypy = "^0.770"
black = "^19.10b0"
isort = { version = "^4.3", extras = ["pyproject"] }
pytest = "^6.0"
tox = "^3.15"
pre-commit = "^2.5"

[["pyproject.toml".tool.poetry.source]]
name = "flow-pypi"
url = "http://flow-pypi.herokuapp.com/simple/"

["pyproject.toml".build-system]
equires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
