["pyproject.toml".tool.poetry.dependencies]
python = "^3.8"

["pyproject.toml".tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.15"  # Linting
mypy                     = "^0.812" # Linting
black                    = "^21b"   # Formatting
isort                    = "^5.0"   # Formatting
unimport                 = "^0.8"   # Formatting
pytest                   = "^6.0"   # Tests
tox                      = "^3.0"   # Tests
pre-commit               = "^2.10"  # Code Style

[["pyproject.toml".tool.poetry.source]]
name = "tec-pypi"
url  = "https://pypi.theengineering.company"

["pyproject.toml".build-system]
build-backend = "poetry.core.masonry.api"
