[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/andreoliwa/nitpick
    hooks:
      - id: nitpick

  - repo: https://github.com/commitizen-tools/commitizen
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/asottile/pyupgrade
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  
  - repo: https://github.com/asottile/add-trailing-comma
    hooks:
      - id: add-trailing-comma
"""
