[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/hakancelik96/unimport
    hooks:
      - id: unimport
        additional_dependencies: [toml]
        args: [--config, pyproject.toml, --remove, --include-star-import]
"""
